# General build settings
[build]
  # Base directory for the build (equivalent to "Base directory: Frontend")
  base = "Frontend"
  # Directory where the built site is output (equivalent to "Publish directory: Frontend/dist")
  publish = "dist"
  # Build command to run (equivalent to "Build command: npm run build")
  command = "npm run build"
  # Directory where Netlify Functions are stored (equivalent to "Functions directory: Frontend/netlify/functions")
  functions = "netlify/functions"

# Functions configuration
[functions]
  # Use esbuild as the Node.js bundler for functions
  node_bundler = "esbuild"

# Environment variables
[build.environment]
  # Specify Node.js version for consistency (Runtime: Not set, defaulting to a stable version)
  NODE_VERSION = "18"

# Redirects for single-page applications (SPA) like Vue.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Dev settings for local development
[dev]
  # Command to run your local development server
  command = "npm run dev"
  # Port for local development
  port = 8888
  # Enable auto-reloading
  publish = "Frontend/dist"